name: Deploy to Hosting Platform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v2
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Deploy to Hosting Platform
        run: |
          # Add your deployment commands here
          # For example, deploy to Heroku:
          # heroku login -i
          # heroku create
          # git push heroku main
